### ISSUE TITLE
Something wrong with EncodedVideo in load_and_transform_video_data 

### ISSUE THREAD

**Issue by anas2908** [facebookresearch/ImageBind#102]
if load_and_transform_video_data is used instead od load_and_transform_vision_data for using video instead of image there rises and error with EncodedVideo and sample_rate

**Comment by anas2908** [comment]
it was my fault sorry

**Comment by ayaan-together** [comment]
What was the fix?

**Comment by elmoghany** [comment]
fix was
opne this file path-to/imagebind/data.py
go to line :317
comment the following line
```
            #**{"sample_rate": sample_rate},
```
