### ISSUE TITLE
Running into lots of dependency issues 

### ISSUE THREAD

**Issue by jackyliang** [facebookresearch/ImageBind#116]
I am trying to use ImageBind on my M2 Mac using Conda, and I have so far run into a ton of dependency issues, including the following. Some I was able to kind of fix, such as VTK, GEOS, and Cartopy, but I could not so far get the `torch==1.13` error to go away

### Summary of Dependency Issues

1. **VTK Dependency**:
   - Error: `Could not find a version that satisfies the requirement vtk`
   - Details: No matching distribution found for vtk during installation.

2. **GEOS Library Missing**:
   - Error: `fatal error: 'geos_c.h' file not found`
   - Details: `cartopy` installation failed due to missing GEOS library.

3. **Torch Version Compatibility**:
   - Error: `Could not find a version that satisfies the requirement torch==1.13.0`
   - Details: `torch==1.13.0` is not available, causing installation issues.

4. **Build Failure for Cartopy**:
   - Error: `error: command '/usr/bin/clang' failed with exit code 1`
   - Details: Failed to build wheel for `cartopy` due to missing dependencies.

The specific error for `torch==1.13.0` looks like this

```
ERROR: Could not find a version that satisfies the requirement torch==1.13.0+cu116 (from imagebind) (from versions: 2.2.0, 2.2.1, 2.2.2, 2.3.0)
ERROR: No matching distribution found for torch==1.13.0
```

**Comment by ChrisjanWust** [comment]
For the pytorch error: this probably has to do with the fact that you're using a newer version of Python. Try installing with python 3.8. 

Regarding the other errors: no idea - I'm running into the same problems.

**Comment by ChrisjanWust** [comment]
We've done a couple of fixes that should have ironed out all the issues with running the repo. Let me know if you still have issues @jackyliang .
