### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'bpe/bpe_simple_vocab_16e6.txt.gz'

### ISSUE THREAD

**Issue by atakui1** [facebookresearch/ImageBind#15]
![Uploading 截屏2023-05-10 11.44.03.png…]()

**Comment by yincangshiwei** [comment]
Hello, this file is located in the BPE folder of the root directory.
![image](https://github.com/facebookresearch/ImageBind/assets/8185843/f9f27cd5-c766-44b5-bba9-3364bbcf61c0)
