### ISSUE TITLE
No module named 'models'

### ISSUE THREAD

**Issue by luisangelico** [facebookresearch/ImageBind#26]
from models import imagebind_model

ModuleNotFoundError: No module named 'models'

I tried using jupyter notebook and spyder. I've already tried to changing enviroments also.

Any idea?

**Comment by sachinspanicker** [comment]
Hi,
extract the models, bpe and assets folder along with the files inside from the git and keep it in a directory locally and at the same level as the folders, keep the extracted data.py, requirements.txt and also create a python file with the code given in the Usage section where it starts from import data. Thereafter, run the following 3 lines and then execute the python file you created. That should solve it.

conda create --name imagebind python=3.8 -y
conda activate imagebind

pip install -r requirements.txt
