### ISSUE TITLE
Google colab link for generating images or audio

### ISSUE THREAD

**Issue by chjayakrishnajk** [facebookresearch/ImageBind#43]
I have tried to run the code in README, it ran successfully

But how I can generate images or audio by prompt like "cat meow"

**Comment by ikuinen** [comment]
> 

Maybe try this repo: https://github.com/sail-sg/BindDiffusion

**Comment by ikuinen** [comment]
> I have tried to run the code in README, it ran successfully
> 
> But how I can generate images or audio by prompt like "cat meow"

Maybe try this repo: https://github.com/sail-sg/BindDiffusion

**Comment by chjayakrishnajk** [comment]
I got the repo

**Comment by chjayakrishnajk** [comment]
See also [Anything2Image](https://github.com/Zeqiang-Lai/Anything2Image) and [InternGPT](https://github.com/OpenGVLab/InternGPT), it is implemented with Diffusers.
