### ISSUE TITLE
The link to the paper is marked as "TBD" instead of providing a valid link

### ISSUE THREAD

**Issue by gautham2k3** [facebookresearch/ImageBind#7]
The issue is that in the introduction section of the document, the link to the paper is marked as "TBD" instead of providing a valid link. This should be fixed by adding the correct link to the paper.

` **[ImageBind: One Embedding Space To Bind Them All](TBD)**`

**Comment by rohitgirdhar** [comment]
Thanks for raising the issue! fixed.
