### ISSUE TITLE
Is there plan for release the training code?

### ISSUE THREAD

**Issue by EthanZhangCN** [facebookresearch/ImageBind#80]
In fact, I want to bind another modal, how do I get started?

**Comment by LinB203** [comment]
> In fact, I want to bind another modal, how do I get started?


Hi, here to recommend our [work](https://github.com/PKU-YuanGroup/LanguageBind), which is _LanguageBind: Extending Video-Language Pretraining to N-modality by Language-based Semantic Alignment_.  **We open source all training and validation code.**
