### ISSUE TITLE
Simply replacing Detic's CLIP-based ‘class’ enbedding with imagebind audio embedding

### ISSUE THREAD

**Issue by youngstear** [facebookresearch/ImageBind#91]
Thanks for your good jobs!!!
I tried this, audio embedding dim of imagebind is 1024,  but Detic model need embedding of 512 dim，Can you release matched model？For example，imagebind_base.pth？

**Comment by ChrisjanWust** [comment]
Unfortunately you'll need to train your own conversion model to convert to Detic's embedding space. All ImageBind embeddings are 1024dims.
